apiVersion: apps/v1
kind: Deployment
metadata:
  name: encrypt-engine-deployment
  namespace: default
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: encrypt-engine
  template:
    metadata:
      labels:
        app: encrypt-engine
    spec:
      containers:
        - name: encrypt-engine-container
          image: 466015366405.dkr.ecr.eu-north-1.amazonaws.com/encrypt-engine:1.0
          
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: encrypt-engine-config
            - secretRef:
                name: encrypt-engine-secret